force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Object used to track individual job applications.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>Date to indicate when it&apos;s time to follow up on the submitted application.</description>
    <inlineHelpText>Please enter a date you intend to follow up.</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This holds the status of the job application.</description>
    <inlineHelpText>Please choose a status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationStaleTest.cls
@isTest
public class JobApplicationStaleTest {

    static testmethod void testJobApplicationStale() {
        List<Job_Application__c> staleJobs = new List<Job_Application__c>();

        Job_Application__c oldJob = new Job_Application__c(Name = 'Test Job App', Status__c = 'Closed', Follow_up_Date__c = System.Today().addDays(-30));
        staleJobs.add(oldJob);

        Job_Application__c oldJob2 = new Job_Application__c(Name = 'Test Job App2', Status__c = 'Accepted', Follow_up_Date__c = System.Today().addDays(-30));
        staleJobs.add(oldJob2);

        insert staleJobs;

        System.assertEquals('Closed', oldJob.Status__c);
        System.assertEquals('Accepted', oldJob2.Status__c);

        JobApplicationStale sch = new JobApplicationStale();
        sch.execute(null);
        
    }
}