force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Object used to track individual job applications.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to store the name of the company for the application.</description>
    <inlineHelpText>Please choose the name of the company for this application.</inlineHelpText>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This holds the status of the job application.</description>
    <inlineHelpText>Please choose a status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerTest.cls
@istest
public with sharing class JobApplicationTriggerTest {
    
 @istest
    public static void testJobApplicationTrigger_updateTask(){
        //Bulk test data preparation
        Account bulkTestAccount = new Account( 
          Name = 'Test Job Co'
        );
        insert bulkTestAccount;

        // Bulk create new Job Applications
      List<Job_Application__c> bulkTaskTest = new List<Job_Application__c>();
        for (Integer i = 0; i < 300; i++) {
            bulkTaskTest.add(new Job_Application__c(
              Name = 'Bulk Test' + i, 
              Status__c = 'Saved',
              Company_Name__c = bulkTestAccount.Id
            ));
        }
        insert bulkTaskTest;

        List<Task> newTasks = [
          SELECT WhatId, Subject
          FROM Task
          WHERE WhatId
          IN :bulkTaskTest
        ];
  
        for (Task bulkTaskCheck : newTasks){
          System.assertEquals(300, newTasks.size(), 'Bulk Tasks did not update');
        }

        List <Job_Application__c> jobsList = new List <Job_Application__c>();
          jobsList.add(new Job_Application__c(
          Name = 'Test 1',
          Status__c = 'Applying'
        ));
        jobsList.add(new Job_Application__c(
          Name = 'Test 2',
          Status__c = 'Applied'
        ));
        jobsList.add(new Job_Application__c(
          Name = 'Test 3',
          Status__c = 'Interviewing'
        ));
        jobsList.add(new Job_Application__c(
          Name = 'Test 4',
          Status__c = 'Closed'
        ));
        jobsList.add(new Job_Application__c(
          Name = 'Test 5',
          Status__c = 'Accepted'
        ));
        jobsList.add(new Job_Application__c(
          Name = 'Test 6',
          Status__c = 'Negotiating'
        ));

        insert jobsList;

        List<Job_Application__c> updateJobList = [
          SELECT Name, Status__c
          FROM Job_Application__c
          WHERE Status__c = 'Closed'
        ];

        for (Job_Application__c updateCheck : updateJobList){
          if (updateCheck.Name == 'Test 3' ){
              updateCheck.Status__c = 'Closed';
          }
        }
          update updateJobList;

          List<Task> newTasksList = [
            SELECT WhatId, Subject
            FROM Task
            WHERE WhatId
            IN :updateJobList
        ];
  
        for (Task updateTaskCheck : newTasksList){
          System.assertEquals(1, newTasksList.size(), 'Task did not update');
        }
      }
    }