force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Object used to track individual job applications.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>Date to indicate when it&apos;s time to follow up on the submitted application.</description>
    <inlineHelpText>Please enter a date you intend to follow up.</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This holds the status of the job application.</description>
    <inlineHelpText>Please choose a status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationStale.cls
global class JobApplicationStale implements Schedulable {

    global void execute (SchedulableContext Sc) {
        List<Job_Application__c> staleJobs = [
            SELECT Id, Status__c, LastModifiedDate, Name, Follow_up_Date__c
            FROM Job_Application__c
            WHERE (Status__c != 'Closed' OR Status__c = 'Accepted') 
            AND Follow_up_Date__c > LAST_N_DAYS:30
        ];

        if(!staleJobs.isEmpty()){

            List<Job_Application__c> closedJobs = new List<Job_Application__c>();

            for (Job_Application__c updateJobs : staleJobs){
                updateJobs.Status__c = 'Closed';
                updateJobs.Notes__c = 'This Job Application has not been updated in more than 30 days and was closed by an automation.';
                }

                update closedJobs;
        }
    }

}