force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>holds the name of the Primary contact</description>
    <inlineHelpText>Who is the primary contact for this account?</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Object used to track individual job applications.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to store the name of the company for the application.</description>
    <inlineHelpText>Please choose the name of the company for this application.</inlineHelpText>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to hold the primary contact.</description>
    <inlineHelpText>Who is the Primary Contact?</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrimaryContactHandlerTest.cls
@isTest
public class PrimaryContactHandlerTest {
    @isTest
    static void testPrimaryContactHandler() {
        Account testAccount = new Account(Name = 'Test Account' );
        insert testAccount;
        Contact testContact = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            AccountId = testAccount.Id
        );
        insert testContact;
        Job_Application__c oldJob = new Job_Application__c(
            Name = 'TestingTesting',  
            Company_Name__c = testAccount.Id,
            Primary_Contact__c = testContact.Id
        );
        insert oldJob;
        Account newTestAccount = new Account(Name = 'New Test Account');
        insert newTestAccount;
        Job_Application__c newJob = new Job_Application__c(Name = 'TestingAgain', Company_Name__c = newTestAccount.Id);
        insert newJob;
        Account accountWithoutPrimaryContact = new Account(Name = 'Account Without Primary Contact');
        insert accountWithoutPrimaryContact;
        Job_Application__c jobWithoutPrimaryContact = new Job_Application__c(Name = 'TestingThirdTime', Company_Name__c = accountWithoutPrimaryContact.Id);
        insert jobWithoutPrimaryContact;
        jobWithoutPrimaryContact.Company_Name__c = testAccount.Id;
        update jobWithoutPrimaryContact;
        Job_Application__c updatedJobWithoutPrimaryContact = [SELECT Primary_Contact__c FROM Job_Application__c WHERE Id = :jobWithoutPrimaryContact.Id];
        System.assertEquals(null, updatedJobWithoutPrimaryContact.Primary_Contact__c);
        }
  
    @isTest
    static void testPrimaryContactHandlerWithAccountChange() {
        Account testAccount = new Account(Name = 'Test Account' );
        insert testAccount;
        Contact testContact = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            AccountId = testAccount.Id
        );
        insert testContact;
        Account newTestAccount = new Account(Name = 'New Test Account');
        insert newTestAccount;
        Job_Application__c newJob = new Job_Application__c(Name = 'TestingAgain', Company_Name__c = newTestAccount.Id);
        insert newJob;
        newJob.Company_Name__c = testAccount.Id;
        update newJob;
        Job_Application__c updatedJob = [SELECT Primary_Contact__c FROM Job_Application__c WHERE Id = :newJob.Id];
        System.assertEquals(testContact.Id, updatedJob.Primary_Contact__c);
    }
}