force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>holds the name of the Primary contact</description>
    <inlineHelpText>Who is the primary contact for this account?</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Object used to track individual job applications.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to store the name of the company for the application.</description>
    <inlineHelpText>Please choose the name of the company for this application.</inlineHelpText>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to hold the primary contact.</description>
    <inlineHelpText>Who is the Primary Contact?</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrimaryContactHandler.cls
public with sharing class PrimaryContactHandler {
    public static void setPrimaryContact(Job_Application__c job, Job_Application__c oldJob) {
        if (job != null && oldJob != null) {
            if (job.Company_Name__c != oldJob.Company_Name__c) {
                job.Primary_Contact__c = null;
                if (job.Company_Name__c != null) {
                    Id primaryContactId = null;
                    //move SOQL queries out of the for loop and save the values
                    Map<Id, Account> accountMap = new Map<Id, Account>();
                    Map<Id, Contact> contactMap = new Map<Id, Contact>();
                    List<Account> relatedAccounts = [SELECT Id, Primary_Contact__c FROM Account WHERE Id IN :new Set<Id>{job.Company_Name__c}];
                    for (Account acc : relatedAccounts) {
                        accountMap.put(acc.Id, acc);
                        if (acc.Primary_Contact__c != null) {
                            primaryContactId = acc.Primary_Contact__c;
                        }
                    }
                    if (primaryContactId == null) {
                        //move SOQL out of four loop and save values
                        List<Contact> contacts = [SELECT Id, AccountId FROM Contact WHERE AccountId = :job.Company_Name__c LIMIT 1];
                        for (Contact con : contacts) {
                            contactMap.put(con.AccountId, con);
                            primaryContactId = con.Id;
                        }
                    }
                    if (primaryContactId != null) {
                        job.Primary_Contact__c = primaryContactId;
                    }
                }
            }
        }
    }
}